"""empty message

Revision ID: 513cee00e08b
Revises: 
Create Date: 2023-09-18 09:03:05.729204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513cee00e08b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
